# Generated by Django 3.1.1 on 2020-09-30 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SongAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Accounts.vieuser'),
            preserve_default=False,
        ),
    ]
