# Generated by Django 3.1.1 on 2020-10-06 09:21

import StorageBackend.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongAPI', '0003_song_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, storage=StorageBackend.custom_storage.MusicStorage(), upload_to=''),
        ),
    ]
