# Generated by Django 3.1.1 on 2020-10-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongAPI', '0004_auto_20201006_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
