# Generated by Django 3.1.1 on 2021-02-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongAPI', '0005_auto_20201006_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
