# Generated by Django 3.1.1 on 2020-09-29 09:50

import StorageBackend.custom_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SongAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('thumbnail', models.FileField(blank=True, null=True, storage=StorageBackend.custom_storage.MediaStorage(), upload_to='playlist-thumbnail')),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('songs', models.ManyToManyField(blank=True, related_name='playlists', to='SongAPI.Song')),
            ],
            options={
                'ordering': ['created_datetime'],
            },
        ),
    ]
