# Generated by Django 3.1.1 on 2021-03-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlaylistAPI', '0002_auto_20200929_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
